services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres
    command: >
      /bin/sh -c "
        echo 'Esperando que Postgres esté disponible...';
        while ! nc -z postgres 5432; do sleep 1; done;
        echo 'Postgres disponible. Iniciando Metabase.';
        /app/run_metabase.sh
      "
    networks:
      - metanet

  postgres:
    image: postgres:15
    container_name: metabase_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    networks:
      - metanet

volumes:
  metabase_db_data:

networks:
  metanet:
    driver: bridge
